name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . --file app/Dockerfile --tag luvisjostonj/fastapi:v1
        docker push luvisjostonj/fastapi:v1

    - name: Log out from Docker Hub
      run: docker logout

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -i fastapi/pem.pem ubuntu@ec2-34-224-27-126.compute-1.amazonaws.com << 'EOF'
        docker pull luvisjostonj/fastapi:v1
        docker stop your_container_name || true
        docker rm your_container_name || true
        docker run -d --name joston -p 8000:8000 luvisjostonj/fastapi:v1
        EOF
